// Generated by ts-to-zod
import { z } from "zod";

export const costSchema = z.object({
  wood: z.number(),
  food: z.number(),
  gold: z.number(),
  stone: z.number(),
});

export const unitsBuildingSchema = z.object({
  cost: costSchema,
  attack: z.number(),
  melee_armor: z.number(),
  pierce_armor: z.number(),
  base_id: z.number(),
  help_converter: z.number(),
  language_file_name: z.number(),
  language_file_help: z.number(),
  name: z.string(),
  hit_points: z.number(),
  line_of_sight: z.number(),
  garrison_capacity: z.number(),
  type: z.number(),
  class: z.number(),
});

export const techSchema = z.object({
  cost: costSchema,
  help_converter: z.number(),
  language_file_name: z.number(),
  language_file_help: z.number(),
  name: z.string(),
});

export const unitsBuildingsTechsSchema = z.object({
  units_buildings: z.record(unitsBuildingSchema),
  techs: z.record(techSchema),
});
